name: Build Flutter APK

on:
  push:
    branches:
      - feature/bix-social-media-app

jobs:
  build:
    name: Build bix app APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release || true  # تجاهل الأخطاء كما طلبت

      - name: Upload APK
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: bix-app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
